# Deployment: под Redis (кэш + rate limiting), без персистентности, 1 реплика.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-redis
  namespace: todo-app
  labels:
    app: redis

spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      nodeSelector:
        kubernetes.io/hostname: k8s-worker2
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
      containers:
        - name: redis
          image: redis:7-alpine
          command: ["redis-server"]
          args: ["--requirepass", "$(REDIS_PASSWORD)"]
          envFrom:
            - secretRef:
                name: app-secret
          ports:
            - containerPort: 6379
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "200m"

          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - "REDISCLI_AUTH=$REDIS_PASSWORD redis-cli --no-auth-warning ping"
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
